### ISSUE TITLE
Autoclicker

### ISSUE THREAD

**Issue by orangemonkey01** [ekoerp1/School-Hacks-You-Need-Bookmarklets-#10]
here is a better one

javascript:clicker:{const{Number}=self;const milliseconds=Number.parseInt(self.prompt("How many seconds do you want to wait before clicking again?",%271%27),10);if(false===Number.isSafeInteger(milliseconds)){self.alert("Input was not an integer");break clicker;}let clientX=0,clientY=0;const{document}=self;self.setInterval(()=>{document.elementFromPoint(clientX,clientY)?.click?.();},milliseconds);document.addEventListener("mousemove",event=>{({clientX,clientY}=event);},{passive:true});}

**Comment by ekoerp1** [comment]
Thanks!
